name: Run Script Periodically

on:
  schedule:
    - cron: '45 * * * *'  # Isso fará com que o script execute a cada hora. Altere conforme necessário.
  workflow_dispatch:  # Permite a execução manual do workflow.

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use a versão do Python que você precisa.

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv requests atproto  # Adicione outras dependências conforme necessário.

      - name: Run the script
        env:
          BLUESKY_EMAIL: ${{ secrets.BLUESKY_EMAIL }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        run: python basic_script.py
